// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_process.proto

package iochti.process.grpc;

public final class DataProcessProto {
  private DataProcessProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProcessData_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_ProcessData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022data_process.proto\022\005proto\032\033google/prot" +
      "obuf/empty.proto\032\037google/protobuf/timest" +
      "amp.proto\"\203\001\n\013ProcessData\022\n\n\002id\030\001 \001(\t\022\022\n" +
      "\ndataTypeId\030\002 \001(\t\022\024\n\014thingGroupId\030\003 \001(\t\022" +
      "-\n\tcreatedAt\030\004 \001(\0132\032.google.protobuf.Tim" +
      "estamp\022\017\n\007payload\030\005 \001(\t2F\n\013DataProcess\0227" +
      "\n\007Process\022\022.proto.ProcessData\032\026.google.p" +
      "rotobuf.Empty\"\000B$\n\016iochti.processB\020DataP" +
      "rocessProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_proto_ProcessData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ProcessData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_proto_ProcessData_descriptor,
        new java.lang.String[] { "Id", "DataTypeId", "ThingGroupId", "CreatedAt", "Payload", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
