// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data_process.proto

package iochti.process.grpc;

public interface ProcessDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ProcessData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string dataTypeId = 2;</code>
   */
  java.lang.String getDataTypeId();
  /**
   * <code>optional string dataTypeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataTypeIdBytes();

  /**
   * <code>optional string thingGroupId = 3;</code>
   */
  java.lang.String getThingGroupId();
  /**
   * <code>optional string thingGroupId = 3;</code>
   */
  com.google.protobuf.ByteString
      getThingGroupIdBytes();

  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 4;</code>
   */
  boolean hasCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 4;</code>
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <code>optional .google.protobuf.Timestamp createdAt = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <code>optional string payload = 5;</code>
   */
  java.lang.String getPayload();
  /**
   * <code>optional string payload = 5;</code>
   */
  com.google.protobuf.ByteString
      getPayloadBytes();
}
